using System.IO.Compression; using System.Text; using GSPTaskMiningAnalyzer.Models;
namespace GSPTaskMiningAnalyzer;
public sealed class ExcelReportService
{
    static readonly string[] Sheets = ["Dashboard","Daily","Hourly","Applications","WindowTitles","Sessions","ProcessChains","Screenshots","Errors","RawData"];
    public string Write(AnalysisResult r,string output,bool raw)
    {
        Directory.CreateDirectory(output); var path=Path.Combine(output,$"task_mining_report_{DateTime.Now:yyyyMMdd_HHmmss}.xlsx"); using var z=ZipFile.Open(path,ZipArchiveMode.Create);
        var sheetNames = raw ? Sheets : Sheets.Where(s=>s!="RawData").ToArray();
        Add(z,"[Content_Types].xml","<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"xml\" ContentType=\"application/xml\"/><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/>"+string.Concat(Enumerable.Range(1,sheetNames.Length).Select(i=>$"<Override PartName=\"/xl/worksheets/sheet{i}.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/>"))+"</Types>");
        Add(z,"_rels/.rels","<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>");
        Add(z,"xl/_rels/workbook.xml.rels","<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">"+string.Concat(Enumerable.Range(1,sheetNames.Length).Select(i=>$"<Relationship Id=\"rId{i}\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet{i}.xml\"/>"))+"</Relationships>");
        Add(z,"xl/workbook.xml","<workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets>"+string.Concat(sheetNames.Select((n,i)=>$"<sheet name=\"{n}\" sheetId=\"{i+1}\" r:id=\"rId{i+1}\"/>"))+"</sheets></workbook>");
        for(int i=0;i<sheetNames.Length;i++) Add(z,$"xl/worksheets/sheet{i+1}.xml",SheetXml(sheetNames[i],r)); return path;
    }
    static string SheetXml(string name,AnalysisResult r){var rows=new List<string>{Row(name,"Value"),Row("Active",Fmt(r.ActiveSeconds)),Row("Idle",Fmt(r.IdleSeconds)),Row("Events",r.Events.Count.ToString()),Row("Sessions",r.Sessions.Count.ToString())}; if(name=="Applications") rows.AddRange(r.AppSeconds.OrderByDescending(x=>x.Value).Select(x=>Row(x.Key,Fmt(x.Value)))); if(name=="Sessions") rows.AddRange(r.Sessions.Take(500).Select(s=>Row(s.ProcessName,$"{s.Start:O} - {s.End:O} {Fmt(s.DurationSeconds)}"))); if(name=="ProcessChains") rows.AddRange(r.Chains2.OrderByDescending(x=>x.Value).Select(x=>Row(x.Key,x.Value.ToString()))); if(name=="Errors") rows.AddRange(r.Errors.Select(e=>Row(e,""))); return $"<worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><sheetViews><sheetView workbookViewId=\"0\"><pane ySplit=\"1\" topLeftCell=\"A2\" activePane=\"bottomLeft\" state=\"frozen\"/></sheetView></sheetViews><sheetData>{string.Concat(rows.Select((x,i)=>$"<row r=\"{i+1}\">{x}</row>"))}</sheetData><autoFilter ref=\"A1:B1\"/></worksheet>";}
    static string Row(string a,string b)=>$"<c t=\"inlineStr\"><is><t>{Esc(a)}</t></is></c><c t=\"inlineStr\"><is><t>{Esc(b)}</t></is></c>"; static string Fmt(double s){var h=(int)(s/3600);var m=(int)((s%3600)/60);return h>0?$"{h} ч {m} мин":$"{m} мин";} static string Esc(string s)=>System.Security.SecurityElement.Escape(s)??""; static void Add(ZipArchive z,string n,string c){var e=z.CreateEntry(n); using var w=new StreamWriter(e.Open(),new UTF8Encoding(false)); w.Write(c);} }
