using System.IO.Compression; using System.Text; using GSPTaskMiningAnalyzer.Models;
namespace GSPTaskMiningAnalyzer;
public sealed class ExcelReportService
{
    static readonly string[] Sheets = ["Дашборд","Динамика по дням","Динамика по часам","Приложения","Операции","Сессии","Цепочки процессов","Кандидаты на автоматизацию","Скриншоты","Ошибки","Исходные данные"];
    public string Write(AnalysisResult r,string output,bool raw)
    {
        Directory.CreateDirectory(output); var path=Path.Combine(output,$"task_mining_report_{DateTime.Now:yyyyMMdd_HHmmss}.xlsx"); using var z=ZipFile.Open(path,ZipArchiveMode.Create);
        var sheetNames = raw ? Sheets : Sheets.Where(s=>s!="Исходные данные").ToArray();
        Add(z,"[Content_Types].xml","<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"xml\" ContentType=\"application/xml\"/><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/>"+string.Concat(Enumerable.Range(1,sheetNames.Length).Select(i=>$"<Override PartName=\"/xl/worksheets/sheet{i}.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/>"))+"<Override PartName=\"/xl/charts/chart1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.drawingml.chart+xml\"/></Types>");
        Add(z,"_rels/.rels","<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>");
        Add(z,"xl/_rels/workbook.xml.rels","<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">"+string.Concat(Enumerable.Range(1,sheetNames.Length).Select(i=>$"<Relationship Id=\"rId{i}\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet{i}.xml\"/>"))+"</Relationships>");
        Add(z,"xl/workbook.xml","<workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets>"+string.Concat(sheetNames.Select((n,i)=>$"<sheet name=\"{Esc(n)}\" sheetId=\"{i+1}\" r:id=\"rId{i+1}\"/>"))+"</sheets></workbook>");
        for(int i=0;i<sheetNames.Length;i++) Add(z,$"xl/worksheets/sheet{i+1}.xml",SheetXml(sheetNames[i],r));
        Add(z,"xl/charts/chart1.xml","<c:chartSpace xmlns:c=\"http://schemas.openxmlformats.org/drawingml/2006/chart\"><c:chart><c:title><c:tx><c:rich><a:bodyPr xmlns:a=\"http://schemas.openxmlformats.org/drawingml/2006/main\"/><a:p xmlns:a=\"http://schemas.openxmlformats.org/drawingml/2006/main\"><a:r><a:t>Динамика по часам</a:t></a:r></a:p></c:rich></c:tx></c:title><c:plotArea/></c:chart></c:chartSpace>"); return path;
    }
    static string SheetXml(string name,AnalysisResult r){var rows=new List<string>{Row(name,"Значение"),Row("Активное время",Fmt(r.ActiveSeconds)),Row("Простой",Fmt(r.IdleSeconds)),Row("Компьютер заблокирован",Fmt(r.LockedSeconds)),Row("События",r.Events.Count.ToString()),Row("Уникальных событий",r.UniqueEvents.ToString()),Row("Удалено дублей",r.DuplicatesRemoved.ToString()),Row("Сессии",r.Sessions.Count.ToString())}; if(name=="Приложения") rows.AddRange(r.AppSeconds.OrderByDescending(x=>x.Value).Select(x=>Row(x.Key,Fmt(x.Value)))); if(name=="Сессии") rows.AddRange(r.Sessions.Take(500).Select(s=>Row(s.ProcessName,$"{s.Start:dd.MM.yyyy HH:mm:ss} - {s.End:dd.MM.yyyy HH:mm:ss} {Fmt(s.DurationSeconds)}"))); if(name=="Цепочки процессов") rows.AddRange(r.Chains2.OrderByDescending(x=>x.Value).Select(x=>Row(x.Key,x.Value.ToString()))); if(name=="Кандидаты на автоматизацию") rows.AddRange(r.AutomationOpportunities.Select(o=>Row(o.Name,$"{o.AutomationScore}: {o.RecommendedSolution}; {o.Rationale}"))); if(name=="Ошибки") rows.AddRange(r.Errors.Select(e=>Row(e,""))); return $"<worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><sheetViews><sheetView workbookViewId=\"0\"><pane ySplit=\"1\" topLeftCell=\"A2\" activePane=\"bottomLeft\" state=\"frozen\"/></sheetView></sheetViews><cols><col min=\"1\" max=\"2\" width=\"36\" customWidth=\"1\"/></cols><sheetData>{string.Concat(rows.Select((x,i)=>$"<row r=\"{i+1}\">{x}</row>"))}</sheetData><autoFilter ref=\"A1:B1\"/></worksheet>";}
    static string Row(string a,string b)=>$"<c t=\"inlineStr\"><is><t>{Esc(a)}</t></is></c><c t=\"inlineStr\"><is><t>{Esc(b)}</t></is></c>"; static string Fmt(double s){var d=(int)(s/86400);var h=(int)((s%86400)/3600);var m=(int)((s%3600)/60);var sec=(int)(s%60); if(d>0)return $"{d} д {h} ч"; if(h>0)return $"{h} ч {m} мин"; if(m>0)return $"{m} мин {sec} сек"; return $"{sec} сек";} static string Esc(string s)=>System.Security.SecurityElement.Escape(s)??""; static void Add(ZipArchive z,string n,string c){var e=z.CreateEntry(n); using var w=new StreamWriter(e.Open(),new UTF8Encoding(false)); w.Write(c);} }
